language: ruby
cache:
- bundler
notifications:
  slack:
    rooms:
      - $SLACK_TOKEN
    on_pull_requests: false
script: bundle exec middleman build --clean
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  on:
    branch: master
